apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: trust-self
spec:
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: foobar-api-ingress
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`foobar-api.localhost`)
    kind: Rule
    middlewares:
      - name: foobar-api-auth
      - name: rate-limit
    services:
    - name: foobar-api-svc
      port: 80
      scheme: https
      serversTransport: trust-self
  tls:
    certResolver: myresolver
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`traefik.localhost`)
    kind: Rule
    middlewares:
      - name: foobar-api-auth
    services:
    - name: api@internal
      kind: TraefikService
